//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingPlatform {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class InterfacePath : global::System.Configuration.ApplicationSettingsBase {
        
        private static InterfacePath defaultInstance = ((InterfacePath)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InterfacePath())));
        
        public static InterfacePath Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/trading/order/add")]
        public string maimai {
            get {
                return ((string)(this["maimai"]));
            }
            set {
                this["maimai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/trading/position/list")]
        public string chicang {
            get {
                return ((string)(this["chicang"]));
            }
            set {
                this["chicang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/trading/order/list")]
        public string weituo {
            get {
                return ((string)(this["weituo"]));
            }
            set {
                this["weituo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/trading/trade/list")]
        public string chengjiaojilu {
            get {
                return ((string)(this["chengjiaojilu"]));
            }
            set {
                this["chengjiaojilu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/common/mqttInfo")]
        public string mqttinfo {
            get {
                return ((string)(this["mqttinfo"]));
            }
            set {
                this["mqttinfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/user/login")]
        public string bussinelogin {
            get {
                return ((string)(this["bussinelogin"]));
            }
            set {
                this["bussinelogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://market.future.alibaba.com/exchange/list")]
        public string jiaoyisuo {
            get {
                return ((string)(this["jiaoyisuo"]));
            }
            set {
                this["jiaoyisuo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/trading/order/cancel")]
        public string chedan {
            get {
                return ((string)(this["chedan"]));
            }
            set {
                this["chedan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/trading/order/list")]
        public string tiaojiandan {
            get {
                return ((string)(this["tiaojiandan"]));
            }
            set {
                this["tiaojiandan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://market.future.alibaba.com/contract/list/detail")]
        public string hangqinglist {
            get {
                return ((string)(this["hangqinglist"]));
            }
            set {
                this["hangqinglist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://market.future.alibaba.com/contract/detail")]
        public string heyuepeizhi {
            get {
                return ((string)(this["heyuepeizhi"]));
            }
            set {
                this["heyuepeizhi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/auth/login/pass")]
        public string Login {
            get {
                return ((string)(this["Login"]));
            }
            set {
                this["Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/auth/register")]
        public string Register {
            get {
                return ((string)(this["Register"]));
            }
            set {
                this["Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/auth/checkCode/send")]
        public string SendMessage {
            get {
                return ((string)(this["SendMessage"]));
            }
            set {
                this["SendMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/auth/checkCode/verify")]
        public string CheckMessageCode {
            get {
                return ((string)(this["CheckMessageCode"]));
            }
            set {
                this["CheckMessageCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/auth/login/sms")]
        public string LoginOrRegisterByCode {
            get {
                return ((string)(this["LoginOrRegisterByCode"]));
            }
            set {
                this["LoginOrRegisterByCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/auth/refreshToken")]
        public string RefreshToken {
            get {
                return ((string)(this["RefreshToken"]));
            }
            set {
                this["RefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/auth/resetPass")]
        public string ResetPassWord {
            get {
                return ((string)(this["ResetPassWord"]));
            }
            set {
                this["ResetPassWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/info")]
        public string GetUserInfo {
            get {
                return ((string)(this["GetUserInfo"]));
            }
            set {
                this["GetUserInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://front.future.alibaba.com/user/info/update")]
        public string UpdateUserInfo {
            get {
                return ((string)(this["UpdateUserInfo"]));
            }
            set {
                this["UpdateUserInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trade.xgj.alibaba.com/user/logout")]
        public string bussineloginout {
            get {
                return ((string)(this["bussineloginout"]));
            }
            set {
                this["bussineloginout"] = value;
            }
        }
    }
}
